### ISSUE TITLE
Fails at install

### ISSUE THREAD

**Issue by moondawg69** [webmenedzser/craft-reporter#1]
Latest version of Craft, tried to install via the Plugin Store.

<img width="718" alt="Screenshot 2020-01-30 at 22 19 44" src="https://user-images.githubusercontent.com/1304000/73495605-cc595b00-43ae-11ea-9253-b14ac305bf1e.png">

**Comment by Saboteur777** [comment]
I will look into it, thanks for opening this issue! 

In the meantime: you can click *Leave it uninstalled*, navigate to Plugins settings page and install it there: it should install fine.

**Comment by Saboteur777** [comment]
Thanks for reporting, fixed in [1.5.1](https://github.com/webmenedzser/craft-reporter/blob/master/CHANGELOG.md#v151---2020-01-31).
